### ISSUE TITLE
Unhandled NullPointer in Chrome Extension

### ISSUE THREAD

**Issue by mardapol** [satsukitv/twitter-block-chain#78]
When running the Blockchain in Chrome, the following log appears:

Error in event handler: TypeError: Cannot read property '1' of null                                                                 NPDHamburg:1 
    at MobileTwitter.getProfileUsername (chrome-extension://dkkfampndkdnjffkleokegfnibnnjfah/js/blockchain.js:263:88)
    at isOnTheRightPage (chrome-extension://dkkfampndkdnjffkleokegfnibnnjfah/js/blockchain.js:44:20)
    at chrome-extension://dkkfampndkdnjffkleokegfnibnnjfah/js/blockchain.js:49:13
    at onMessage (chrome-extension://dkkfampndkdnjffkleokegfnibnnjfah/js/browser-polyfill.min.js:869:24)

**Comment by mardapol** [comment]
After digging deeper into the code, this seems to be caused by pop up blockers. If deactivated, the script works finde.
